
server:
  port: 8761


eureka:
  # 以下配置仅在开发环境中使用
  # 关闭注册中心的自我保护机制，防止已关闭的实例无法从注册中心剔除
  server:
    enable-self-preservation: false
  client:
    # 把自己注册到 eureka
    register-with-eureka: false
    # 取来 eureka 注册表
    fetch-registry: false
    serviceUrl:
      # 注册中心地址
      defaultZone: http://localhost:${server.port}/eureka/
