
server:
  port: 8762

spring:
  application:
    # 应用名称
    name: hello-spring-cloud-consumer

feign:
  circuitbreaker:
    enabled: true #开启熔断支持


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      # 使用 ip 代替实例名
      prefer-ip-address: true
      # 实例的主机名
      hostname: ${spring.cloud.client.ip-address}
      # 实例的 ID 规则
      instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}


