server:
  port: 8760

spring:
  application:
    name: hello-spring-cloud-config-server
  # git 保存配置文件
  cloud:
    config:
      server:
        git:
          # 仓库地址
          uri: https://github.com/myinsert/spring-cloud-config-warehouse
          # Git 的分支
          default-label: master
          # 仓库文件夹名称，多个以逗号分隔
          search-paths:
          # git 仓库用户名（公开库可以不用填写
          username:
          # git 仓库密码（公开库可以不用填写）
          password:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
      # 使用 ip 代替实例名
      prefer-ip-address: true
      # 实例的主机名
      hostname: ${spring.cloud.client.ip-address}
      # 实例的 ID 规则
      instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}